### PR TITLE
Wayland: Build with VAAPI wayland patches

### PR DESCRIPTION
**Pull request by EliasOfWaffle**
The main ideia is for build using vaapi patches from aur https://aur.archlinux.org/packages/chromium-wayland-vaapi

And sorry for my old pull request.

### CODE REVIEW

**Comment by refi64** [comment]
This has [come up before](https://github.com/flathub/org.chromium.Chromium/issues/187), and unfortunately I still don't think this is something that belongs here. It's a multi-year old patch that was already outdated when created and was known to be a bit buggy at the time (both of these were outlined in the commit message). I'm not familiar enough with this code to be able to debug and rebase it on a new releases.

Chromium *does* also support this nowadays, just in a somewhat roundabout way (it goes through Vulkan). I have absolutely zero idea how that works, but I have equally zero idea how the old path that this patch uses works too.

**Comment by EliasOfWaffle** [comment]
> This has [come up before](https://github.com/flathub/org.chromium.Chromium/issues/187), and unfortunately I still don't think this is something that belongs here. It's a multi-year old patch that was already outdated when created and was known to be a bit buggy at the time (both of these were outlined in the commit message). I'm not familiar enough with this code to be able to debug and rebase it on a new releases.
> 
> Chromium _does_ also support this nowadays, just in a somewhat roundabout way (it goes through Vulkan). I have absolutely zero idea how that works, but I have equally zero idea how the old path that this patch uses works too.

Sorry but this patch not need to be adapt, the source from chromium wayland aur is building, this patch is working in a test, and the vaapi works now with new VaapiDecodeLinuxGL this is the way to get vaapi in OpenGL 
The CI/CD have builded and this is a proof from a user that had tested this artifact build, but had problems with older intel gpus generations, this not working for some whatever reason


7f3c5e65-7a8c-4103-81c0-60578522f2b4

**Comment by EliasOfWaffle** [comment]
@refi64

**Comment by EliasOfWaffle** [comment]
For run is necessary this flags 
--enable-features=VaapiVideoDecodeLinuxGL
--ozone-platform-hint=wayland

**Comment by EliasOfWaffle** [comment]
@refi64

**Comment by tankaras** [comment]
@refi64 Please re-open and merge. Chromium team don't care about their implementation of vaapi. It has had a memory leak [bug](https://gitlab.freedesktop.org/mesa/mesa/-/issues/9220) for a while now under Xwayland with the flag `--enable-features=VaapiVideoDecodeLinuxGL`. 

The wayland patch fixes this problem until Chromium can support vaapi on native Wayland. Have tested with the above mentioned AUR and have no memory leaks.

**Comment by EliasOfWaffle** [comment]
> 

Is better to i create a new merge request or waiting the @refi64 decision ?

**Comment by EliasOfWaffle** [comment]
> @refi64 Please re-open and merge. Chromium team don't care about their implementation of vaapi. It has had a memory leak [bug](https://gitlab.freedesktop.org/mesa/mesa/-/issues/9220) for a while now under Xwayland with the flag `--enable-features=VaapiVideoDecodeLinuxGL`.
> 
> The wayland patch fixes this problem until Chromium can support vaapi on native Wayland. Have tested with the above mentioned AUR and have no memory leaks.

Is better to submit this a new merge request or waiting @refi64 ?

**Pull request closed without merging**
