### PR TITLE
Screenshare

### PR DESCRIPTION
**Pull request by GeorgesStavracas**
Untested. See commits.

Closes https://github.com/flathub/org.chromium.Chromium/issues/22
Closes https://github.com/flathub/org.chromium.Chromium/issues/21

### CODE REVIEW

**Comment by GeorgesStavracas** [comment]
Hm, perhaps Chromium expects pipewire 0.2 to be present?

**Comment by GeorgesStavracas** [comment]
Let's try with 0.2.7

**Comment by GeorgesStavracas** [comment]
Seems to have worked with PipeWire 0.2.7, let's wait for the build to finish

**Comment by GeorgesStavracas** [comment]
It worked:

Captura de tela de 2020-11-19 20-20-44

**Comment by FastOSlinux** [comment]
Captura de tela de 2020-11-19 20-22-00

**Comment by GeorgesStavracas** [comment]
This last build works as a native Wayland client (`--enable-features=UseOzonePlatform --ozone-platform=wayland`), screen sharing works through PipeWire, and Google Meets / Hangouts is able to screenshare too:

Captura de tela de 2020-11-20 10-22-20

**Pull request merged**
