### PR TITLE
Update Chromium to 91.0.4472.77

### PR DESCRIPTION
**Pull request by refi64**

### CODE REVIEW

**Comment by refi64** [comment]
Looks like we crashed Clang...again...

```
clang++ -MMD -MF obj/chrome/browser/ui/ui/tab_strip_region_view.o.d -DUSE_DBUS -DUSE_DBUS_MENU -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_OZONE=1 -DUSE_X11=1 -DOFFICIAL_BUILD -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -DNO_UNWIND_TABLES -D_GNU_SOURCE -DCR_CLANG_REVISION=\"llvmorg-13-init-6429-g0e92cbd6-2\" -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -D_LIBCPP_ABI_UNSTABLE -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCXXABI_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_ENABLE_NODISCARD -D_LIBCPP_HAS_NO_VENDOR_AVAILABILITY_ANNOTATIONS -DCR_LIBCXX_REVISION=8fa87946779682841e21e2da977eccfb6cb3bded -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DUSE_CUPS -DGLIB_VERSION_MAX_ALLOWED=GLIB_VERSION_2_40 -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_40 -DWEBP_EXTERN=extern -DVK_USE_PLATFORM_XCB_KHR -DGL_GLEXT_PROTOTYPES -DUSE_GLX -DUSE_EGL -D_WTL_NO_AUTOMATIC_NAMESPACE -DON_FOCUS_PING_ENABLED -DTOOLKIT_VIEWS=1 -DGOOGLE_PROTOBUF_NO_RTTI -DGOOGLE_PROTOBUF_NO_STATIC_INITIALIZER -DHAVE_PTHREAD -DSK_UNTIL_CRBUG_1187654_IS_FIXED -DSK_FAVOR_WUFFS_V_0_3_OVER_V_0_2 -DSK_CODEC_DECODES_PNG -DSK_CODEC_DECODES_WEBP -DSK_ENCODE_PNG -DSK_ENCODE_WEBP -DSK_USER_CONFIG_HEADER=\"../../skia/config/SkUserConfig.h\" -DSK_GL -DSK_CODEC_DECODES_JPEG -DSK_ENCODE_JPEG -DSK_HAS_WUFFS_LIBRARY -DSK_VULKAN_HEADER=\"../../skia/config/SkVulkanConfig.h\" -DSK_VULKAN=1 -DSK_SUPPORT_GPU=1 -DSK_GPU_WORKAROUNDS_HEADER=\"gpu/config/gpu_driver_bug_workaround_autogen.h\" -DVK_USE_PLATFORM_XCB_KHR -DU_USING_ICU_NAMESPACE=0 -DU_ENABLE_DYLOAD=0 -DUSE_CHROMIUM_ICU=1 -DU_ENABLE_TRACING=1 -DU_ENABLE_RESOURCE_TRACING=0 -DU_STATIC_IMPLEMENTATION -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_FILE -DWEBRTC_ENABLE_AVX2 -DWEBRTC_NON_STATIC_TRACE_EVENT_HANDLERS=0 -DWEBRTC_CHROMIUM_BUILD -DWEBRTC_POSIX -DWEBRTC_LINUX -DABSL_ALLOCATOR_NOTHROW=1 -DWEBRTC_USE_BUILTIN_ISAC_FIX=0 -DWEBRTC_USE_BUILTIN_ISAC_FLOAT=1 -DWEBRTC_USE_X11 -DWEBRTC_HAVE_SCTP -DNO_MAIN_THREAD_WRAPPING -DLEVELDB_PLATFORM_CHROMIUM=1 -DLEVELDB_PLATFORM_CHROMIUM=1 -DCRASHPAD_ZLIB_SOURCE_EXTERNAL -DV8_USE_EXTERNAL_STARTUP_DATA -DATK_LIB_DIR=\"/usr/lib/x86_64-linux-gnu\" -DUSE_ATK_BRIDGE -DV8_COMPRESS_POINTERS -DV8_COMPRESS_POINTERS_IN_ISOLATE_CAGE -DV8_31BIT_SMIS_ON_64BIT_ARCH -DV8_DEPRECATION_WARNINGS -DCPPGC_CAGED_HEAP -DI18N_ADDRESS_VALIDATION_DATA_URL=\"https://chromium-i18n.appspot.com/ssl-aggregate-address/\" -DFLATBUFFERS_LOCALE_INDEPENDENT=0 -DVK_NO_PROTOTYPES -DUSE_VULKAN_XCB -I../.. -Igen -I../../third_party/perfetto/include -Igen/third_party/perfetto/build_config -Igen/third_party/perfetto -I../../third_party/libyuv/include -I../../third_party/jsoncpp/source/include -I../../third_party/libwebp/src -I../../third_party/vulkan-deps/vulkan-headers/src/include -I../../third_party/khronos -I../../gpu -Igen/third_party/dawn/src/include -I../../third_party/dawn/src/include -I../../third_party/wtl/include -I../../third_party/protobuf/src -Igen/protoc_out -I../../third_party/protobuf/src -I../../third_party/abseil-cpp -I../../third_party/boringssl/src/include -Igen/net/third_party/quiche/src -I../../net/third_party/quiche/overrides -I../../net/third_party/quiche/src/common/platform/default -I../../net/third_party/quiche/src -Igen -Igen/third_party/metrics_proto -I../../third_party/skia -I../../third_party/wuffs/src/release/c -I../../third_party/vulkan/include -I../../third_party/vulkan-deps/vulkan-headers/src/include -I../../third_party/icu/source/common -I../../third_party/icu/source/i18n -I../../third_party/ced/src -I../../third_party/webrtc_overrides -I../../third_party/webrtc -Igen/third_party/webrtc -I../../third_party/leveldatabase -I../../third_party/leveldatabase/src -I../../third_party/leveldatabase/src/include -I../../third_party/crashpad/crashpad -I../../third_party/crashpad/crashpad/compat/linux -I../../third_party/crashpad/crashpad/compat/non_win -I../../third_party/zlib -I../../third_party/mesa_headers -I../../third_party/libwebm/source -I../../v8/include -Igen/v8/include -Igen -Igen/components/policy/proto -Igen/third_party/private_membership/src -Igen/third_party/shell-encryption/src -Igen/components/policy/proto -Igen -Igen -I../../third_party/re2/src -Igen -Igen -Igen -Igen -I../../third_party/libaddressinput/src/cpp/include -I../../third_party/tflite/src -Igen/third_party/tflite/src -I../../third_party/flatbuffers/src/include -I../../third_party/tflite-support/src -I../../third_party/tflite-support/src/tensorflow_lite_support -Igen/third_party/tflite-support/src -Igen -I../../third_party/brotli/include -Igen -I../../third_party/fontconfig/src -Igen -Igen -Igen -Igen -Igen -fno-delete-null-pointer-checks -fno-ident -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -fno-unwind-tables -fno-asynchronous-unwind-tables -fPIC -pthread -fcolor-diagnostics -fmerge-all-constants -fcrash-diagnostics-dir=../../tools/clang/crashreports -mllvm -instcombine-lower-dbg-declare=0 -flto=thin -fsplit-lto-unit -fwhole-program-vtables -fcomplete-member-pointers -m64 -march=x86-64 -msse3 -Xclang -fdebug-compilation-dir -Xclang . -no-canonical-prefixes -Wall -Wextra -Wimplicit-fallthrough -Wunreachable-code -Wthread-safety -Wextra-semi -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-unneeded-internal-declaration -Wno-undefined-var-template -Wno-psabi -Wno-ignored-pragma-optimize -Wno-implicit-int-float-conversion -Wno-final-dtor-non-final-class -Wno-builtin-assume-aligned-alignment -Wno-deprecated-copy -Wno-non-c-typedef-for-linkage -Wno-max-tokens -O2 -fdata-sections -ffunction-sections -fno-omit-frame-pointer -g2 -Xclang -debug-info-kind=constructor -ggnu-pubnames -ftrivial-auto-var-init=pattern -fsanitize=cfi-vcall -fsanitize-blacklist=../../tools/cfi/ignores.txt -fsanitize=cfi-icall -fvisibility=hidden -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Wexit-time-destructors -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -DPROTOBUF_ALLOW_DEPRECATED=1 -Wno-shorten-64-to-32 -Wno-header-guard -I/usr/include/nss -I/usr/include/atk-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/at-spi2-atk/2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -std=c++14 -fno-trigraphs -Wno-trigraphs -fno-exceptions -fno-rtti -nostdinc++ -isystem../../buildtools/third_party/libc++/trunk/include -isystem../../buildtools/third_party/libc++abi/trunk/include -fvisibility-inlines-hidden -Wno-deprecated-declarations -Wno-unknown-warning-option -Wno-unknown-pragmas -D_LIBCPP_HAS_NO_VENDOR_AVAILABILITY_ANNOTATIONS -c ../../chrome/browser/ui/views/frame/tab_strip_region_view.cc -o obj/chrome/browser/ui/ui/tab_strip_region_view.o
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: clang++ -MMD -MF obj/chrome/browser/ui/ui/tab_strip_region_view.o.d -DUSE_DBUS -DUSE_DBUS_MENU -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_OZONE=1 -DUSE_X11=1 -DOFFICIAL_BUILD -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -DNO_UNWIND_TABLES -D_GNU_SOURCE -DCR_CLANG_REVISION=\"llvmorg-13-init-6429-g0e92cbd6-2\" -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -D_LIBCPP_ABI_UNSTABLE -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCXXABI_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_ENABLE_NODISCARD -D_LIBCPP_HAS_NO_VENDOR_AVAILABILITY_ANNOTATIONS -DCR_LIBCXX_REVISION=8fa87946779682841e21e2da977eccfb6cb3bded -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DUSE_CUPS -DGLIB_VERSION_MAX_ALLOWED=GLIB_VERSION_2_40 -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_40 -DWEBP_EXTERN=extern -DVK_USE_PLATFORM_XCB_KHR -DGL_GLEXT_PROTOTYPES -DUSE_GLX -DUSE_EGL -D_WTL_NO_AUTOMATIC_NAMESPACE -DON_FOCUS_PING_ENABLED -DTOOLKIT_VIEWS=1 -DGOOGLE_PROTOBUF_NO_RTTI -DGOOGLE_PROTOBUF_NO_STATIC_INITIALIZER -DHAVE_PTHREAD -DSK_UNTIL_CRBUG_1187654_IS_FIXED -DSK_FAVOR_WUFFS_V_0_3_OVER_V_0_2 -DSK_CODEC_DECODES_PNG -DSK_CODEC_DECODES_WEBP -DSK_ENCODE_PNG -DSK_ENCODE_WEBP -DSK_USER_CONFIG_HEADER=\"../../skia/config/SkUserConfig.h\" -DSK_GL -DSK_CODEC_DECODES_JPEG -DSK_ENCODE_JPEG -DSK_HAS_WUFFS_LIBRARY -DSK_VULKAN_HEADER=\"../../skia/config/SkVulkanConfig.h\" -DSK_VULKAN=1 -DSK_SUPPORT_GPU=1 -DSK_GPU_WORKAROUNDS_HEADER=\"gpu/config/gpu_driver_bug_workaround_autogen.h\" -DVK_USE_PLATFORM_XCB_KHR -DU_USING_ICU_NAMESPACE=0 -DU_ENABLE_DYLOAD=0 -DUSE_CHROMIUM_ICU=1 -DU_ENABLE_TRACING=1 -DU_ENABLE_RESOURCE_TRACING=0 -DU_STATIC_IMPLEMENTATION -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_FILE -DWEBRTC_ENABLE_AVX2 -DWEBRTC_NON_STATIC_TRACE_EVENT_HANDLERS=0 -DWEBRTC_CHROMIUM_BUILD -DWEBRTC_POSIX -DWEBRTC_LINUX -DABSL_ALLOCATOR_NOTHROW=1 -DWEBRTC_USE_BUILTIN_ISAC_FIX=0 -DWEBRTC_USE_BUILTIN_ISAC_FLOAT=1 -DWEBRTC_USE_X11 -DWEBRTC_HAVE_SCTP -DNO_MAIN_THREAD_WRAPPING -DLEVELDB_PLATFORM_CHROMIUM=1 -DLEVELDB_PLATFORM_CHROMIUM=1 -DCRASHPAD_ZLIB_SOURCE_EXTERNAL -DV8_USE_EXTERNAL_STARTUP_DATA -DATK_LIB_DIR=\"/usr/lib/x86_64-linux-gnu\" -DUSE_ATK_BRIDGE -DV8_COMPRESS_POINTERS -DV8_COMPRESS_POINTERS_IN_ISOLATE_CAGE -DV8_31BIT_SMIS_ON_64BIT_ARCH -DV8_DEPRECATION_WARNINGS -DCPPGC_CAGED_HEAP -DI18N_ADDRESS_VALIDATION_DATA_URL=\"https://chromium-i18n.appspot.com/ssl-aggregate-address/\" -DFLATBUFFERS_LOCALE_INDEPENDENT=0 -DVK_NO_PROTOTYPES -DUSE_VULKAN_XCB -I../.. -Igen -I../../third_party/perfetto/include -Igen/third_party/perfetto/build_config -Igen/third_party/perfetto -I../../third_party/libyuv/include -I../../third_party/jsoncpp/source/include -I../../third_party/libwebp/src -I../../third_party/vulkan-deps/vulkan-headers/src/include -I../../third_party/khronos -I../../gpu -Igen/third_party/dawn/src/include -I../../third_party/dawn/src/include -I../../third_party/wtl/include -I../../third_party/protobuf/src -Igen/protoc_out -I../../third_party/protobuf/src -I../../third_party/abseil-cpp -I../../third_party/boringssl/src/include -Igen/net/third_party/quiche/src -I../../net/third_party/quiche/overrides -I../../net/third_party/quiche/src/common/platform/default -I../../net/third_party/quiche/src -Igen -Igen/third_party/metrics_proto -I../../third_party/skia -I../../third_party/wuffs/src/release/c -I../../third_party/vulkan/include -I../../third_party/vulkan-deps/vulkan-headers/src/include -I../../third_party/icu/source/common -I../../third_party/icu/source/i18n -I../../third_party/ced/src -I../../third_party/webrtc_overrides -I../../third_party/webrtc -Igen/third_party/webrtc -I../../third_party/leveldatabase -I../../third_party/leveldatabase/src -I../../third_party/leveldatabase/src/include -I../../third_party/crashpad/crashpad -I../../third_party/crashpad/crashpad/compat/linux -I../../third_party/crashpad/crashpad/compat/non_win -I../../third_party/zlib -I../../third_party/mesa_headers -I../../third_party/libwebm/source -I../../v8/include -Igen/v8/include -Igen -Igen/components/policy/proto -Igen/third_party/private_membership/src -Igen/third_party/shell-encryption/src -Igen/components/policy/proto -Igen -Igen -I../../third_party/re2/src -Igen -Igen -Igen -Igen -I../../third_party/libaddressinput/src/cpp/include -I../../third_party/tflite/src -Igen/third_party/tflite/src -I../../third_party/flatbuffers/src/include -I../../third_party/tflite-support/src -I../../third_party/tflite-support/src/tensorflow_lite_support -Igen/third_party/tflite-support/src -Igen -I../../third_party/brotli/include -Igen -I../../third_party/fontconfig/src -Igen -Igen -Igen -Igen -Igen -fno-delete-null-pointer-checks -fno-ident -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -fno-unwind-tables -fno-asynchronous-unwind-tables -fPIC -pthread -fcolor-diagnostics -fmerge-all-constants -fcrash-diagnostics-dir=../../tools/clang/crashreports -mllvm -instcombine-lower-dbg-declare=0 -flto=thin -fsplit-lto-unit -fwhole-program-vtables -fcomplete-member-pointers -m64 -march=x86-64 -msse3 -Xclang -fdebug-compilation-dir -Xclang . -no-canonical-prefixes -Wall -Wextra -Wimplicit-fallthrough -Wunreachable-code -Wthread-safety -Wextra-semi -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-unneeded-internal-declaration -Wno-undefined-var-template -Wno-psabi -Wno-ignored-pragma-optimize -Wno-implicit-int-float-conversion -Wno-final-dtor-non-final-class -Wno-builtin-assume-aligned-alignment -Wno-deprecated-copy -Wno-non-c-typedef-for-linkage -Wno-max-tokens -O2 -fdata-sections -ffunction-sections -fno-omit-frame-pointer -g2 -Xclang -debug-info-kind=constructor -ggnu-pubnames -ftrivial-auto-var-init=pattern -fsanitize=cfi-vcall -fsanitize-blacklist=../../tools/cfi/ignores.txt -fsanitize=cfi-icall -fvisibility=hidden -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Wexit-time-destructors -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -DPROTOBUF_ALLOW_DEPRECATED=1 -Wno-shorten-64-to-32 -Wno-header-guard -I/usr/include/nss -I/usr/include/atk-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/at-spi2-atk/2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -std=c++14 -fno-trigraphs -Wno-trigraphs -fno-exceptions -fno-rtti -nostdinc++ -isystem../../buildtools/third_party/libc++/trunk/include -isystem../../buildtools/third_party/libc++abi/trunk/include -fvisibility-inlines-hidden -Wno-deprecated-declarations -Wno-unknown-warning-option -Wno-unknown-pragmas -D_LIBCPP_HAS_NO_VENDOR_AVAILABILITY_ANNOTATIONS -c ../../chrome/browser/ui/views/frame/tab_strip_region_view.cc -o obj/chrome/browser/ui/ui/tab_strip_region_view.o
1.	<eof> parser at end of file
2.	Per-module optimization passes
3.	Running pass 'ThinLTO Bitcode Writer' on module '../../chrome/browser/ui/views/frame/tab_strip_region_view.cc'.
 #0 0x00007fb6f0dc6605 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/usr/lib/sdk/llvm12/lib/libLLVM-12.so+0x1977605)
 #1 0x00007fb6f0dc4584 llvm::sys::RunSignalHandlers() (/usr/lib/sdk/llvm12/lib/libLLVM-12.so+0x1975584)
 #2 0x00007fb6f0dc5c10 llvm::sys::CleanupOnSignal(unsigned long) (/usr/lib/sdk/llvm12/lib/libLLVM-12.so+0x1976c10)
 #3 0x00007fb6f0d0e089 CrashRecoverySignalHandler(int) (/usr/lib/sdk/llvm12/lib/libLLVM-12.so+0x18bf089)
 #4 0x00007fb6ef0c5880 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x39880)
 #5 0x00007fb6f1708f71 (anonymous namespace)::ModuleBitcodeWriter::writeConstants(unsigned int, unsigned int, bool) (/usr/lib/sdk/llvm12/lib/libLLVM-12.so+0x22b9f71)
 #6 0x00007fb6f16f62ff (anonymous namespace)::ModuleBitcodeWriter::write() (/usr/lib/sdk/llvm12/lib/libLLVM-12.so+0x22a72ff)
 #7 0x00007fb6f16f16bf llvm::BitcodeWriter::writeModule(llvm::Module const&, bool, llvm::ModuleSummaryIndex const*, bool, std::array<unsigned int, 5ul>*) (/usr/lib/sdk/llvm12/lib/libLLVM-12.so+0x22a26bf)
 #8 0x00007fb6f1d44c9b (anonymous namespace)::writeThinLTOBitcode(llvm::raw_ostream&, llvm::raw_ostream*, llvm::function_ref<llvm::AAResults& (llvm::Function&)>, llvm::Module&, llvm::ModuleSummaryIndex const*) (/usr/lib/sdk/llvm12/lib/libLLVM-12.so+0x28f5c9b)
 #9 0x00007fb6f1d454b6 (anonymous namespace)::WriteThinLTOBitcode::runOnModule(llvm::Module&) (/usr/lib/sdk/llvm12/lib/libLLVM-12.so+0x28f64b6)
#10 0x00007fb6f0f00d98 llvm::legacy::PassManagerImpl::run(llvm::Module&) (/usr/lib/sdk/llvm12/lib/libLLVM-12.so+0x1ab1d98)
#11 0x00007fb6f4c05eed clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::DataLayout const&, llvm::Module*, clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >) (/usr/lib/sdk/llvm12/lib/libclang-cpp.so.12+0x1c23eed)
#12 0x00007fb6f4ec2038 clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) (/usr/lib/sdk/llvm12/lib/libclang-cpp.so.12+0x1ee0038)
#13 0x00007fb6f3f58ae3 clang::ParseAST(clang::Sema&, bool, bool) (/usr/lib/sdk/llvm12/lib/libclang-cpp.so.12+0xf76ae3)
#14 0x00007fb6f4ebecd3 clang::CodeGenAction::ExecuteAction() (/usr/lib/sdk/llvm12/lib/libclang-cpp.so.12+0x1edccd3)
#15 0x00007fb6f564987a clang::FrontendAction::Execute() (/usr/lib/sdk/llvm12/lib/libclang-cpp.so.12+0x266787a)
#16 0x00007fb6f55d02a1 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/usr/lib/sdk/llvm12/lib/libclang-cpp.so.12+0x25ee2a1)
#17 0x00007fb6f56b637e clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/usr/lib/sdk/llvm12/lib/libclang-cpp.so.12+0x26d437e)
#18 0x00000000002135d7 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/usr/lib/sdk/llvm12/bin/clang-12+0x2135d7)
#19 0x0000000000211ab3 ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) (/usr/lib/sdk/llvm12/bin/clang-12+0x211ab3)
#20 0x00007fb6f5294216 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, bool*) const::$_1>(long) (/usr/lib/sdk/llvm12/lib/libclang-cpp.so.12+0x22b2216)
#21 0x00007fb6f0d0de05 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/usr/lib/sdk/llvm12/lib/libLLVM-12.so+0x18bee05)
#22 0x00007fb6f52938f4 clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, bool*) const (/usr/lib/sdk/llvm12/lib/libclang-cpp.so.12+0x22b18f4)
#23 0x00007fb6f5265e67 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&) const (/usr/lib/sdk/llvm12/lib/libclang-cpp.so.12+0x2283e67)
#24 0x00007fb6f5266323 clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) const (/usr/lib/sdk/llvm12/lib/libclang-cpp.so.12+0x2284323)
#25 0x00007fb6f527bfd4 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) (/usr/lib/sdk/llvm12/lib/libclang-cpp.so.12+0x2299fd4)
#26 0x0000000000211537 main (/usr/lib/sdk/llvm12/bin/clang-12+0x211537)
#27 0x00007fb6ef0b0062 __libc_start_main ../csu/libc-start.c:308:16
#28 0x000000000020e90e _start /buildstream/freedesktop-sdk/bootstrap/glibc.bst/csu/../sysdeps/x86_64/start.S:122:0
clang++: error: clang frontend command failed with exit code 139 (use -v to see invocation)
```

**Comment by Erick555** [comment]
@refi64 I'm not siure if going back and forth with llvm versions is right solution. Could you try if LTO patch alone fixes this?

**Comment by refi64** [comment]
@Erick555 the problem more is that new releases include security fixes, and we've already well passed my general 24 hour goal for pushing out major updates. I'll play with things more after this is out to determine the issue, but we do need at least *some* updated version available.

I don't believe the LTO patch would affect it, though; IIRC it was solely related to parallelization tweaks and shouldn't result in any noticeable behavior changes other than maybe build times.

**Comment by refi64** [comment]
Currently this seems to work on my end, but HiDPI support does not seem to be working (this is on a Wayland host compositor).

**Comment by refi64** [comment]
Actually this does seem to be [documented breakage](https://bugs.chromium.org/p/chromium/issues/detail?id=1213347&q=hidpi%20linux&can=2), we can apply the fix commit ourselves (it was reverted due to Chromedriver breakage, but we don't have Chromedriver atm anyway).

**Comment by refi64** [comment]
So this only seems to affect GTK_DPI_SCALE which isn't often used, with that in mind I'm going to be merging this as-is and will try to backport an upstream fix once it's available.

**Comment by Erick555** [comment]
@refi64 

> I don't believe the LTO patch would affect it, though; IIRC it was solely related to parallelization tweaks and shouldn't result in any noticeable behavior changes other than maybe build times.

I can imagine scenarios like parallelization -> increased memory use -> crash of compiler due to oom or something. This is just a wild guess which is why it's worth checking it the issue is reproducible.

**Pull request merged**
