### PR TITLE
Update Chromium to 90.0.4430.72, combined w/ other open PRs

### PR DESCRIPTION
**Pull request by refi64**
This includes the contents of #86, #88, and #89. @gasinvein this also includes the fix for the terribly stupid portal bug I accidentally added in #89.

### CODE REVIEW

**Comment by refi64** [comment]
```
Failed to download sources: module chromium: Can't find file at (null)
```

Well this is certainly interesting...

**Comment by refi64** [comment]
WELL it looks like we hit a compiler bug, @Erick555 looks like we might be switching to LLVM 11 more quickly than I thought 😅 pulled in your commit from #84 so we'll see if that helps...

**Comment by refi64** [comment]
Well, looks like LLVM 11 is resulting in other build errors...

After some thought, I believe the best course of action is going to end up being to move to the upstream toolchain at least on x64, which is where the compile crashes were occurring anyway. This also avoids the original concern of longer build times when using the upstream toolchain (the x64 one is prebuilt).

We could, of course, just update for LLVM 11 and try to switch to that, but the fact that there's *already* something upstream is uses that 11 doesn't is already a pretty harrowing start.

**Comment by Erick555** [comment]
@refi64 please try this patch https://chromium.googlesource.com/chromium/src/+/9909f146b28d56c9c0411329a056ed959b33f76a

**Comment by Erick555** [comment]
I agree about trying upstream toolchain but I'm not sure what will be the fastest fix to unstuck the build. The backlog is quite big now.

**Comment by Erick555** [comment]
Another alternative is to wait for [llvm12](https://github.com/flathub/flathub/pull/2262) on flathub.

**Comment by refi64** [comment]
@Erick555 thanks for the info, I've added a patch to revert that, so hopefully this will build now.

**Comment by gasinvein** [comment]
It works, #53 and #78 seem to be fixed to me.

**Pull request merged**
