### PR TITLE
Move to 23.08 runtime bump sdk extensions and drop leftover stuff

### PR DESCRIPTION
**Pull request by Erick555**
Fixes https://github.com/flathub/org.chromium.Chromium/issues/344

### CODE REVIEW

**Comment by Erick555** [comment]
@refi64 please review

**Comment by EliasTheGrandMasterOfMistakes** [comment]
This can working good with wayland vaapi patches because of vaapi driver updates

**Comment by refi64** [comment]
bot, build

**Comment by refi64** [comment]
I'll give this some testing over the week (may or may not have PTSD from previous runtime updates gone rogue).

**Comment by EliasTheGrandMasterOfMistakes** [comment]
What you think about this? can be good for new version?
https://github.com/flathub/org.chromium.Chromium/pull/343/commits/9ab3de73fc33957c13660074535444a5f052b3d5

**Comment by refi64** [comment]
Been using for a bit now with no apparent issues, so merging. Thanks!

**Pull request merged**
