### PR TITLE
Pass PipeWire capturer by default and remove socket access

### PR DESCRIPTION
**Pull request by vchernin**
Solves #121 and #148

### CODE REVIEW

**Comment by vchernin** [comment]
What is happening with cobalt here?
```
(cobalt:316): cobalt-DEBUG: 00:23:01.941: Loading config file '/app/etc/cobalt.ini'
(cobalt:316): cobalt-DEBUG: 00:23:01.941: Inferred application name 'chromium'
(cobalt:316): cobalt-DEBUG: 00:23:01.942: Exec= line is: /app/bin/chromium %U
(cobalt:316): cobalt-DEBUG: 00:23:01.942: Zypak is not available (/app/bin/zypak-wrapper.sh not found)
(cobalt:316): cobalt-DEBUG: 00:23:01.942: Inferred ExposePids as 'required' because Zypak is not being used
(cobalt:316): cobalt-DEBUG: 00:23:01.942: Flextop is available
(cobalt:316): cobalt-DEBUG: 00:23:01.944: expose-pids is available
(cobalt:316): cobalt-DEBUG: 00:23:01.949: Flags file '/var/home/v/.var/app/org.chromium.Chromium/config/chromium-flags.conf' not found
(cobalt:316): cobalt-DEBUG: 00:23:01.949: setenv: TMPDIR=/run/user/1000/app/org.chromium.Chromium
(cobalt:316): cobalt-DEBUG: 00:23:01.949: setenv: CHROME_WRAPPER=/app/bin/chromium
(cobalt:316): cobalt-DEBUG: 00:23:01.949: Arg: '/app/chromium/chrome'
(cobalt:316): cobalt-DEBUG: 00:23:01.949: Arg: '--disable-features=WebRTCPipeWireCapturer,WebAssemblyTrapHandler'
```
Why is it disabling `WebRTCPipeWireCapturer`, and `WebAssemblyTrapHandler` for that matter?

**Comment by refi64** [comment]
@vchernin this was a [very, very silly bug in Cobalt](https://github.com/refi64/cobalt/commit/8a49246a97fcb989b370c20b204324862d79541f), the latest version should fix it (disabling `WebAssemblyTrapHandler` is required for #104)

**Comment by vchernin** [comment]
Thanks for fixing that (those ones are always fun!). Hopefully this next build works.

**Comment by vchernin** [comment]
Seems to work as intended.

I can even run with default settings and run `G_MESSAGES_DEBUG=cobalt flatpak run org.chromium.Chromium//test --enable-features=UseOzonePlatform --ozone-platform=wayland`

gives in chrome://gpu
```
Command Line	/app/chromium/chrome --enable-features=WebRTCPipeWireCapturer,UseOzonePlatform --disable-features=WebAssemblyTrapHandler --ozone-platform=wayland --enable-crashpad --flag-switches-begin --flag-switches-end
```

So everything looks right. Cobalt's doing its job :)

**Comment by refi64** [comment]
Is there a reason this is still draft then?

**Comment by vchernin** [comment]
No, there wasn't

**Comment by vchernin** [comment]
Oh, should I rebase?

**Comment by refi64** [comment]
I personally prefer rebasing but it's not really a huge deal so I'm just merging it in anyway, thanks!!

**Comment by vchernin** [comment]
No problem! and I'll make sure to rebase next time then :)

**Pull request merged**
